services:
  - type: web
    name: photo-mgmt-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: photo-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false # Set this manually in the Render Dashboard

databases:
  - name: photo-db
    plan: free